---
- name: Hashi Vault Ansible Demo
  hosts: localhost
  gather_facts: False
  become: False

# first make sure the following Environment variables are set
# export VAULT_TOKEN=`cat ~/.vault-token`
# VAULT_ADDR=https://vault.prod.yet.org
#
# you then can run the demo
# ansible-playbook read_secret.yaml

  tasks:
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=kv/bookshelf validate_certs=False')}}"